services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    command: npm run dev
  server:
    build: ./server
    ports:
      - "9000:9000"
    volumes:
      - ./server/src:/app/src
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CI=false
    command: npm run dev
