services:
  client:
    build: ./client
    volumes:
      - ./client/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run test
  server:
    build: ./server
    volumes:
      - ./server/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run test
