name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx (for building multi-platform images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Cache Docker layers for faster builds
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Build and push client Docker image
      - name: Build client Docker image
        run: |
          docker-compose -f docker-compose.yml build client

      # Build and push server Docker image
      - name: Build server Docker image
        run: |
          docker-compose -f docker-compose.yml build server

      # Run Docker Compose (client & server) to start the services
      - name: Run Docker Compose up
        run: |
          docker-compose -f docker-compose.yml up -d

      # Run Linting for both client and server
      - name: Run Client Linting
        run: docker-compose exec client npm run lint

      - name: Run Server Linting
        run: docker-compose exec server npm run lint

      # Run Tests for both client and server
      - name: Run Client Tests
        run: docker-compose exec client npm test

      - name: Run Server Tests
        run: docker-compose exec server npm test

      # Optionally, tear down the containers after testing
      - name: Tear down Docker Compose
        run: |
          docker-compose -f docker-compose.yml down
