name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Node.js (Client)
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies (Client)
        run: npm install
        working-directory: ./client

      - name: Install dependencies (Server)
        run: npm install
        working-directory: ./server

      - name: Run ESLint (client)
        run: npm run lint
        working-directory: ./client

      - name: Run ESLint (server)
        run: npm run lint
        working-directory: ./server

      - name: Run tests (client)
        run: npm run test
        working-directory: ./client

      - name: Run tests (server)
        run: npm run test
        working-directory: ./server

      - name: Build Docker Client
        run: docker-compose -f docker-compose.yml build client

      - name: Build Docker Server
        run: docker-compose -f docker-compose.yml build server
