name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Step 4: Set up Node.js (Client)
      - name: Set up Node.js (Client)
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      # Step 5: Install dependencies for Client
      - name: Install dependencies (Client)
        run: npm install
        working-directory: ./client

      # Step 6: Install dependencies for Server
      - name: Install dependencies (Server)
        run: npm install
        working-directory: ./server

      # Step 7: Run Docker Compose (Build Client)
      - name: Build Docker Client
        run: docker-compose -f docker-compose.yml build client

      # Add any further steps for running tests, linting, or deployment
